[ADD] Test- und Klassendeklarationen (CodeCharts)
xsoophx/SoftwareEngineering pull request #10
Opened 2020-12-05 14:00 UTC by winkloid

Hinzufügen der Test- und Klassendeklarationen für das CodeCharts-Tool.

2020-12-05 15:08 UTC, xsoophx requested changes

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsSettingsHandler.kt
> +  fun runCodeCharts() {}
sollte eher start() heißen, nur ums einheitlich zu haben

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsSettingsHandler.kt
> +class CodeChartsSettingsHandler {
Sollte einfach CodeChartsTool heißen.

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsSettingsHandler.kt
> +}
Die vier Funktionen können weg, die werden über den Config Manager gecallt.

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsStringHandler.kt
> +  private val generatedStrings = setOf<String>()
Wenn wir die Strings wirklich speichern wollen, müsste das ein private lateinit var sein

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsStringHandler.kt
> +  fun generateStrings(Input: Int) {}
Hier könnte man noch alle erlaubten Zeichen mit als Parameter übergeben. Oder in ner anderen Funktion.

2020-12-05 15:08 UTC, xsoophx commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsStringHandler.kt
> +  fun isInList(InputString: String) {}
Bräuchte man nicht unbedingt, da es die Funktion für Listen schon gibt.

2020-12-05 18:45 UTC, winkloid commented on src/main/code/de/tu_chemnitz/se/exercise/codecharts/CodeChartsInputValidator.kt
> +  fun saveData() {}
Die Methode dient dazu, die im Tool gesammelten Daten zu speichern bzw. an den Datenanalyse-Client zu senden. Ich werde diese Methode nicht nur private setzen, sondern sie sogar aus dieser Klasse entfernen und in den SettingsHandler verschieben, der alle Teilfunktionen des Tools startet und auch alle Daten aus ihnen enthält. Daher ist der SettingsHandler meiner Meinung nach sogar besser zur Umsetzung dieser Methode geeignet, als der Input-Validator

2020-12-05 20:22 UTC, xsoophx approved these changes

2020-12-05 20:23 UTC, winkloid commented
Folgende Änderungen wurden nun noch vorgenommen:

`CodeChartsSettingsHandler` in `CodeChartsTool` umbenannt und Dateinamen entsprechend angepasst.

```
private fun getConfigData() {}
private fun loadConfig() {}
fun saveConfig() {}
fun setConfig() {}
```
aus `CodeChartsTool` entfernt

```
private fun orderList() {}
fun isInList(InputString: String) {}
```
aus StringHandler entfernt,
Deklaration` fun getStrings() {}` hinzugefügt

Parameter `AllowedChars` im StringHandler hinzugefügt, welches erlaubte Zeichen für generierte Strings in derzeit 3 verschiedenen Modi beschreibt (Großbuchstaben, Kleinbuchstaben, Zahlen)

2020-12-06 11:39 UTC, asaskiap approved these changes

2020-12-07 16:16 UTC, PLAYLEX approved these changes

2020-12-07 16:33 UTC, merged