[ADD] CodeChartsStringHandler Tests
xsoophx/SoftwareEngineering pull request #17
Opened 2020-12-15 10:02 UTC by winkloid

Added test bodies for `CodeChartsStringHandler` for the following test cases:
`check whether strings are duplicate`
`check whether list is ordered`
`check whether number of strings is right`

2020-12-15 10:04 UTC, schubertn approved these changes

2020-12-15 15:12 UTC, xsoophx requested changes

2020-12-15 15:12 UTC, xsoophx commented on src/test/code/de/tuchemnitz/se/exercise/codecharts/CodeChartsStringHandlerTest.kt
> +import assertk.assertThat
Bei dem Test würde ich euch am Donnerstag gern noch nen kleinen Trick zeigen :D

2020-12-21 19:08 UTC, xsoophx requested changes

2020-12-21 19:08 UTC, xsoophx commented on src/test/code/de/tuchemnitz/se/exercise/codecharts/CodeChartsStringHandlerTest.kt
> +        assertThat(inputNumber).isEqualTo(generatedStrings.size)
Hier gibts bei einem testcase noch nen Fehler den wir beheben müssten :/

2020-12-21 19:46 UTC, winkloid commented on src/test/code/de/tuchemnitz/se/exercise/codecharts/CodeChartsStringHandlerTest.kt
> +        assertThat(inputNumber).isEqualTo(generatedStrings.size)
Wird vermutlich beim Fall `booleanArrayOf(false, false, false)` sein, da dort nur ein einzelner leerer String zurückgegeben wird.

2020-12-22 09:52 UTC, winkloid commented on src/test/code/de/tuchemnitz/se/exercise/codecharts/CodeChartsStringHandlerTest.kt
> +        assertThat(inputNumber).isEqualTo(generatedStrings.size)
Jetzt sollte alles funktionieren

2020-12-22 13:55 UTC, xsoophx approved these changes

2020-12-22 13:57 UTC, merged