Now we have a view for application start-up
xsoophx/SoftwareEngineering pull request #22
Opened 2021-01-05 17:54 UTC by PLAYLEX

Just select the prefered tool by pressing the button.

2021-01-05 18:01 UTC, winkloid approved these changes

2021-01-05 18:59 UTC, xsoophx requested changes

2021-01-05 18:59 UTC, xsoophx commented on src/main/code/de/tuchemnitz/se/exercise/core/graphics/MainApp.kt
> +         */
Das müsste noch raus

2021-01-05 18:59 UTC, xsoophx commented on src/main/code/de/tuchemnitz/se/exercise/core/graphics/system/ToolSelectionView.kt
> +        // println("Docking Login View!") TODO: logging
Sowas müsste auch raus, oder man haut nen logger hin, bzw. ne logger message.

2021-01-06 12:26 UTC, PLAYLEX commented on src/main/code/de/tuchemnitz/se/exercise/core/graphics/MainApp.kt
> +         */
Done.

2021-01-06 12:26 UTC, PLAYLEX commented on src/main/code/de/tuchemnitz/se/exercise/core/graphics/system/ToolSelectionView.kt
> +        // println("Docking Login View!") TODO: logging
Done.

2021-01-06 15:07 UTC, xsoophx approved these changes

2021-01-06 15:52 UTC, merged